// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMetrics(arg1, arg2) {
  return window['go']['main']['App']['GetMetrics'](arg1, arg2);
}

export function LeerJson(arg1) {
  return window['go']['main']['App']['LeerJson'](arg1);
}
