// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scheduler} from '../models';

export function GetMetrics(arg1:Array<scheduler.Process>,arg2:scheduler.Params):Promise<scheduler.OutputData>;

export function LeerJson(arg1:string):Promise<Array<scheduler.Process>>;
